# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d4db7779cc83ddd1482637d74f3b1b3347a64b047a28806cc752a49342973d9c2ac372ecc5f24ef2bfcace62e39721469f5a16e98ffee189885980c3de71820f

test:
  secret_key_base: ed63ce9a254efbd66529c1f315d14e7bfaf68eab4377b78a1ced97599a7d13f4e74d33b9600b6e8a641c1eda492fcd81181534a41cb642d2e9ebf0dd36ab4f7e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
